Versions freeze
deeppavlov/dialog_flow_framework pull request #111
Opened 2023-04-27 18:15 UTC by pseusys

# Description

Dependency versions frozen, `redis` dependency updated.

# Checklist

- [x] I have covered the code with tests
- [x] I have added comments to my code to help others understand it
- [x] I have updated the documentation to reflect the changes
- [x] I have performed a self-review of the changes

2023-05-05 09:13 UTC, RLKRo requested changes

2023-05-05 09:13 UTC, RLKRo commented on .github/dependabot.yml
Have you checked that dependabot works with our setup?
> [pip and pip-compile #](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#pip-and-pip-compile)

> In addition to supporting updates to `requirements.txt` files, Dependabot supports updates to `pyproject.toml` files if they follow the PEP 621 standard.

2023-05-05 10:54 UTC, pseusys commented on .github/dependabot.yml
Not yet, but it's not working in PR, so we'll never know what configuration will work I guess

2023-05-09 18:53 UTC, RLKRo commented on .github/dependabot.yml
Maybe test this configuration in a separate repository with a similar setup.py file?

2023-05-12 09:03 UTC, merged