Update std_labels.py
deeppavlov/dialog_flow_framework pull request #176
Opened 2023-07-25 12:09 UTC by pseusys

# Description

From now on, `lbl.forward()` transition now works from start (first) label.

# Checklist

- [x] I have covered the code with tests
- [x] I have added comments to my code to help others understand it
- [x] I have updated the documentation to reflect the changes
- [x] I have performed a self-review of the changes

2023-07-25 21:38 UTC, RLKRo requested changes
I'm not sure if the `repeat` transition is also supposed to return `start_label` and not `fallback_label` if it's in the first node.
Regardless, that behavior should be documented.

2023-07-25 21:40 UTC, pseusys commented
Well, technically, the only situation when this could happen is when the current node *is* the start node, so this is the most expected behaviour I can imagine.

2023-07-25 21:55 UTC, RLKRo commented
Repeat is supposed to go to the last visited node before the current one (which doesn't exist in our scenario), so no, that is not an expected behavior.

2023-07-26 14:07 UTC, RLKRo requested changes
If repeat is supposed to point to the current label, then yes, it is the expected behavior.

There are still some changes that I'd like to see:

The `previous` label should also be changed.
Probably in the following way:

1. If `len(ctx.labels) == 1`, return start label.
2. If `len(ctx.labels) == 0`, return fallback label.

All of these changes should be documented and new tests added for these special cases.

2023-07-26 14:41 UTC, pseusys commented
Honestly, I do not think `previous` doesn't work correctly.
1. `ctx.labels[-1]` is the current node.
2. `ctx.labels[-2]` is the previous node.
If we **only** have current node and do not have any previous nodes, `previous` transition should bring us to fallback, shouldn't it?
In this case `start_node` is not different from any other node.

2023-07-26 14:45 UTC, RLKRo commented
If we have only one label in `labels`, that means that we'd done the following path
start_label -> label.
If the transition in `label` is `previous` that should point at the `start_label`.

If there are no labels in `labels`, that means we are currently in the `start_node`, and in that case `previous` should return `fallback_label`.

2023-07-29 17:05 UTC, RLKRo approved these changes

2023-07-31 09:03 UTC, kudep approved these changes

2023-07-31 09:03 UTC, merged