fix custom messenger interface
deeppavlov/dialog_flow_framework pull request #206
Opened 2023-08-29 13:07 UTC by ruthenian8

# Description

move custom messenger interface tutor to web_api folder; add form; modify web application logic

# Checklist

- [ ] I have covered the code with tests
- [ ] I have added comments to my code to help others understand it
- [x] I have updated the documentation to reflect the changes
- [x] I have performed a self-review of the changes

2023-08-31 12:04 UTC, ruthenian8 commented on tutorials/messengers/web_api_interface/5_streamlit_chat.py
> +"""
Backed up to the previous state

2023-09-12 19:23 UTC, RLKRo reviewed
I think this tutorial needs a rework. It has some issues (e.g. every dialog with this interface shares the same context).

I think it would be best if we remove this tutorial and add `CallbackMessengerInterface` and a docstring about messenger interfaces in the `fastapi` tutorial. (also add `CallbackMessengerInterface` in the `websocket_chat` tutorial)

2023-10-02 23:44 UTC, RLKRo requested changes

2023-11-14 23:50 UTC, RLKRo approved these changes
Could you do a review of my changes and squash-merge if all good?

2023-11-16 15:05 UTC, merged