update dashboard workflow
deeppavlov/dialog_flow_framework pull request #211
Opened 2023-09-05 14:03 UTC by ruthenian8

# Description

Update the dashboard workflow based on the instruction for the 'latest' tag.

# Checklist

- [ ] I have covered the code with tests
- [ ] I have added comments to my code to help others understand it
- [ ] I have updated the documentation to reflect the changes
- [x] I have performed a self-review of the changes

2023-09-11 05:54 UTC, pseusys approved these changes
Why no new line in the end?

2023-09-11 21:56 UTC, RLKRo requested changes
The workflow run produced the following warnings:
https://github.com/deeppavlov/dialog_flow_framework/actions/runs/6108912931/job/16578872475#step:4:36

2023-09-11 21:56 UTC, RLKRo commented on .github/workflows/update_dashboard.yml
> +  workflow_dispatch:
I don't think we need it.

2023-09-18 15:55 UTC, RLKRo approved these changes

2023-09-25 09:36 UTC, kudep approved these changes

2023-09-25 09:36 UTC, merged