Healthchecks provided for all context storages
deeppavlov/dialog_flow_framework pull request #279
Opened 2023-11-13 21:58 UTC by pseusys

# Description

Also make command `wait_db` was removed and replaced with `--wait` flag (it will be also valid for #132).

# Checklist

- [x] I have performed a self-review of the changes

TODO: we might want to update (remove) all references of `wait_db` only if this is merged BEFORE #132.

# To Consider

- Add tests (if functionality is changed)
- Update API reference / tutorials / guides
- Update CONTRIBUTING.md (if devel workflow is changed)
- Update `.ignore` files, scripts (such as `lint`), distribution manifest (if files are added/deleted)
- Search for references to changed entities in the codebase

2023-11-20 11:22 UTC, ruthenian8 approved these changes

2023-11-21 01:01 UTC, RLKRo requested changes

2023-11-21 09:17 UTC, pseusys commented on compose.yml
> +      start_period: 30s
These numbers were chosen after local testing; some DB images already have healthchecks included, ther do not.
I wanted all of them to be in equal conditions.

2023-11-21 09:19 UTC, pseusys commented on compose.yml
>    dashboard:
We can, but I am not very familiar with what properties should we test in that cases. If you have a suggestion - I'll research how to add some.

2023-11-22 07:42 UTC, pseusys commented on compose.yml
> +      test: ["CMD-SHELL", "mongosh --norc --quiet --eval 'db.runCommand(\"ping\").ok' localhost:27017/test"]
This is not really posible: we can not disable logging for 1 command only.

2023-11-23 13:53 UTC, merged