Added psuedo-setters for context properties
deeppavlov/dialog_flow_framework pull request #51
Opened 2022-12-14 23:37 UTC by pseusys

2022-12-17 04:13 UTC, kudep requested changes
Omg, why did we add old history of commits?

2022-12-17 04:22 UTC, pseusys commented
I've started this branch from `merge/telegram` by mistake I think, hut I've left only the changes that belong here.

2022-12-17 19:07 UTC, kudep requested changes
- [ ] fix examples

2022-12-17 19:07 UTC, kudep commented on examples/generics/2_buttons.py
> -    ctx.requests[last_index] = last_request
same issue of removing

2022-12-26 13:21 UTC, kudep approved these changes

2022-12-26 13:21 UTC, merged