Processing deprecation
deeppavlov/dialog_flow_framework pull request #61
Opened 2022-12-27 22:49 UTC by pseusys

# Description

PROCESSING removed from keywords

# Checklist

- [x] I have covered the code with tests
- [ ] I have added comments to my code to help others understand it
- [ ] I have updated the documentation to reflect the changes
- [x] I have performed a self-review of the changes

2022-12-28 20:50 UTC, kudep approved these changes

2022-12-29 05:49 UTC, avsakharov approved these changes

2022-12-30 10:12 UTC, RLKRo approved these changes

2023-01-10 08:18 UTC, kudep requested changes
- [x] add a description for both processing  in `keywords.py`

2023-01-11 05:58 UTC, kudep approved these changes

2023-01-11 05:58 UTC, merged