add kwargs to `Pipeline.from_script`
deeppavlov/dialog_flow_framework pull request #78
Opened 2023-02-07 17:01 UTC by RLKRo

# Description

Add the ability to specify keywords in `Pipeline.from_script` to be passed to `Actor.__init__`.
This allows to skip validation:
```
pipeline = Pipeline.from_script(
    script=script,
    start_label=("flow", "start_node"),
    fallback_label=("flow", "fallback_node"),
    validation_stage=False,
)
```

# Checklist

- [x] I have covered the code with tests
- [ ] I have added comments to my code to help others understand it
- [x] I have updated the documentation to reflect the changes
- [x] I have performed a self-review of the changes

2023-02-07 20:50 UTC, kudep requested changes

2023-02-07 20:50 UTC, kudep commented on dff/pipeline/pipeline/pipeline.py
> +        **kwargs,
It should be explicit with doc updating

2023-02-09 08:26 UTC, avsakharov approved these changes

2023-02-13 18:56 UTC, RLKRo commented
This change should be made in #73.

2023-02-13 18:56 UTC, closed without merging