Examples sorting order fixed, theming scripts added to repository
deeppavlov/dialog_flow_framework pull request #79
Opened 2023-02-07 22:17 UTC by pseusys

# Description

*Examples sorting order fixed, theming scripts added to repository.*

# Checklist

- [x] I have covered the code with tests
- [x] I have added comments to my code to help others understand it
- [x] I have updated the documentation to reflect the changes
- [x] I have performed a self-review of the changes

2023-02-10 07:01 UTC, avsakharov commented on docs/source/utils/generate_notebook_links.py
> +def create_notebook_link(file: Path, notebook_path: Path):
Should we have descriptions or comments in this file?

2023-02-10 07:02 UTC, avsakharov commented on docs/source/utils/regenerate_apiref.py
> +def generate_doc_container(file: Path, includes: List[Path]):
And the same question about this file.

2023-02-10 07:04 UTC, avsakharov approved these changes

2023-02-14 15:57 UTC, kudep approved these changes

2023-02-14 21:07 UTC, kudep requested changes
- [x] changes of notebooks
- [x] Alexander's changes request

2023-02-16 23:05 UTC, avsakharov commented
For some reason, when I click on the Script section, the page scale decreases (from 100% to 75%).
![image](https://user-images.githubusercontent.com/92101662/219507589-c3858e6a-583c-4617-aaf1-e4abb39f00b8.png)

2023-02-17 08:13 UTC, avsakharov approved these changes

2023-02-18 10:14 UTC, kudep approved these changes

2023-02-18 10:36 UTC, kudep requested changes
- [x] add into examples telegram

2023-02-18 18:19 UTC, avsakharov commented
- [ ] script/core/message.py Write minimal comments

2023-02-19 15:13 UTC, kudep approved these changes

2023-02-19 15:20 UTC, merged