Release notes added to docs
deeppavlov/dialog_flow_framework pull request #92
Opened 2023-03-04 01:13 UTC by pseusys

# Description

Release descriptions (from GitHub) added to Development section from documentation.

# Checklist

- [x] I have covered the code with tests
- [x] I have added comments to my code to help others understand it
- [x] I have updated the documentation to reflect the changes
- [x] I have performed a self-review of the changes

2023-03-08 10:44 UTC, avsakharov commented
> > I suggest the following improvements:
> > 
> > 1. Can we reduce the font size of the Release V#.#.# headers.
> > 2. Somewhere "Changes" is written with a small letter, somewhere with a capital letter. Somewhere with a colon, somewhere without. Can we get them to the same format?
> 
> The releases page comes directly [from here](https://github.com/deeppavlov/dialog_flow_framework/releases). We could've parsed html in order to change it, but the question is: should we? This will result in (in my opinion) greatly unnecessary buildtime overhead. The font size on GitHub is defined using variables. We can hotfix it using static value, but then again, should we? I would suggest trusting GitHub styles in terms of GUI.

1. The problem is that the Development header and the Releases headers are the same size and have the same level. It doesn't look pretty =( Moreover, I think we should put the Releases in a Release notes section. And the corresponding subheading will be smaller in size.
2. Ok, so it can be fixed directly on the page you mentioned. Then it is not a problem at all.

2023-03-08 15:59 UTC, avsakharov commented
> Is it better now?

Yes, it is. Thanks!

2023-03-08 15:59 UTC, avsakharov approved these changes

2023-03-13 06:43 UTC, kudep requested changes
It's failed for local doc building 
![image](https://user-images.githubusercontent.com/11869257/224626675-f2479a1a-8eee-499f-a876-028178b4e13d.png)

2023-03-19 12:54 UTC, kudep approved these changes

2023-03-19 12:55 UTC, merged